version: 2

updates:
- package-ecosystem: github-actions
  commit-message:
    prefix: chore
    prefix-development: chore
  directory: "/"
  labels:
  - chore ðŸ§¹
  pull-request-branch-name:
    separator: /
  reviewers:
  - unfunco
  schedule:
    day: sunday
    interval: weekly
